@apirul = http://localhost:8080
#@id = "ebfb5396-40b7-44bc-81ae-9c4a0280b0e6"
@id = "2a7e9d31-b144-4970-bb3f-0846c6acfe5a"

GET {{apirul}}/categories HTTP/1.1
Accept: application/json

### 
GET {{apirul}}/categories?active=0 HTTP/1.1
Accept: application/json

###

GET {{apirul}}/categories?page=1&limit=3&active=1 HTTP/1.1
Accept: application/json

###

GET {{apirul}}/categories/{{id}} HTTP/1.1
Accept: application/json

###

POST {{apirul}}/admin/categories HTTP/1.1
Content-Type: application/json
Authorization: Bearer 
Accept: application/json

{
    "name": "New aasasasa",
    "description": "Novamente um test!",
    "active": true,
    "created_at": "2025-02-08",
    "updated_at": "2025-02-08"
}

###

POST {{apirul}}/admin/categories/_delete HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

["4c89cb89-16a0-4d30-a5aa-7d06546dd2ab", "c2e499b9-e382-407b-9506-b828fea03410"]

###

POST {{apirul}}/categories/_get HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN
Accept: application/json

["dbf9a48b-0407-4b9c-85e9-e6b2c38b3955", "2a7e9d31-b144-4970-bb3f-0846c6acfe5a"]
###

GET {{apirul}}/categories/{{id}}/products HTTP/1.1
Accept: application/json

###

PATCH {{apirul}}/admin/categories/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN
Accept: application/json

{
    "name": "New Categoryesss",
    "description": "Novamente um test!",
    "active": "true",
    "created_at": "2025-02-08",
    "updated_at": "2025-02-08"
}

###

DELETE {{apirul}}/admin/categories/{{id}} HTTP/1.1
