@apirul = http://localhost:8080
#@id = "ebfb5396-40b7-44bc-81ae-9c4a0280b0e6"
@id = "dbf9a48b-0407-4b9c-85e9-e6b2c38b3955"

GET {{apirul}}/categories HTTP/1.1

### 
GET {{apirul}}/categories?active=0 HTTP/1.1

###

GET {{apirul}}/categories?page=1&limit=3&active=1 HTTP/1.1

###

GET {{apirul}}/categories/{{id}} HTTP/1.1

###

POST {{apirul}}/categories HTTP/1.1
Content-Type: application/ss
Authorization: Bearer ACCESS-TOKEN

{
    "name": "New Categoryesss",
    "description": "Novamente um test!",
    "active": true,
    "created_at": "2025-02-08",
    "updated_at": "2025-02-08"
}

###

POST {{apirul}}/categories/_delete HTTP/1.1
Content-Type: application/xhtml+xml
Authorization: Bearer ACCESS-TOKEN

["66b9f1d4-5800-43bb-b389-d60fe16c44d4", "c2e499b9-e382-407b-9506-b828fea03410"]

###

POST {{apirul}}/categories/_get HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

["dbf9a48b-0407-4b9c-85e9-e6b2c38b3955", "2a7e9d31-b144-4970-bb3f-0846c6acfe5a"]
###

GET {{apirul}}/categories/{{id}}/products HTTP/1.1


###

PATCH {{apirul}}/categories/{{id}} HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "name": "New Categoryesss",
    "description": "Novamente um test!",
    "active": "true",
    "created_at": "2025-02-08",
    "updated_at": "2025-02-08"
}

###

DELETE {{apirul}}/categories/{{id}} HTTP/1.1
