@apirul = http://localhost:8080
@id = "29f35a07-0e18-45a1-8b7d-7d93e2d2b663"

GET {{apirul}}/products HTTP/1.1

### 
GET {{apirul}}/products?active=0 HTTP/1.1

###

GET {{apirul}}/products?page=2&limit=5&active=1 HTTP/1.1

###

GET {{apirul}}/products/{{id}} HTTP/1.1

###

POST {{apirul}}/products HTTP/1.1
Content-Type: application/json
Authorization: Bearer ACCESS-TOKEN

{
    "name": "Celula",
    "description": "testemado",
    "price": 20.0,
    "active": true,
    "created_at": "2025-02-08",
    "updated_at": "2025-02-08",
    "categoriesIds": ["dbf9a48b-0407-4b9c-85e9-e6b2c38b3955"]
}

###

POST {{apirul}}/products/_delete HTTP/1.1
Content-Type: application/xhtml+xml
Authorization: Bearer ACCESS-TOKEN

["e61d7297-855b-4a43-9131-d1b798e9d74e", "8f658a10-7790-4745-91b6-8f0f9cd4c4ef"]

###

PATCH {{apirul}}/products/{{id}} HTTP/1.1

###

DELETE {{apirul}}/products/{{id}} HTTP/1.1