@apirul = http://localhost:8080
@id = dbf9a48b-0407-4b9c-85e9-e6b2c38b3955

GET {{apirul}}/products HTTP/1.1

### 
GET {{apirul}}/products?active=0 HTTP/1.1

###

GET {{apirul}}/products?page=2&limit=5&active=1 HTTP/1.1

###

GET {{apirul}}/products/{{id}} HTTP/1.1

###

POST {{apirul}}/products HTTP/1.1

###

POST {{apirul}}/products/_delete HTTP/1.1

###

PUT {{apirul}}/products/{{id}} HTTP/1.1

###

DELETE {{apirul}}/products/{{id}} HTTP/1.1